### PR TITLE
Add first public version

### PR DESCRIPTION
**Pull request by JinneeJ**
This PR adds implementation of first public version of kotlin warning plugin.

### CODE REVIEW

**Review by AfzalivE — APPROVED** [review]
This is great! And PR looks good to me. 

It would be great to have releasing instructions as well. The Gradle plugin portal link doesn't work but I'm guessing once we release it, it will?

**Comment by JinneeJ** [comment]
Thanks a lot for the review! 🎉

> Built on my local just fine but I'm not sure how to use my local copy as a plugin to test it out 😅 .

Sorry, instructions for testing was provided in linked PR in Todoist repository :) Let me know if it works!

> It would be great to have releasing instructions as well.

I'm going to setup github action for release later and will update README accordingly :)

> The Gradle plugin portal link doesn't work but I'm guessing once we release it, it will?

Yes :)

**Comment by AfzalivE** [comment]
> Sorry, instructions for testing was provided in linked PR in Todoist repository :) Let me know if it works!

Worked perfectly! Tried on a new Kotlin Multiplatform project too! The only thing I found slightly confusing was that when there were no warnings, no file was created, which made me think that I was doing something wrong 😅 .

**Comment by JinneeJ** [comment]
> The only thing I found slightly confusing was that when there were no warnings, no file was created, which made me think that I was doing something wrong 😅 .

Thanks for feedback! To avoid confusions I've updated description for task `writeKotlinWarningBaseline` in README :)

**Pull request merged**
